FROM node:16

WORKDIR /usr/src/app

COPY ../backend/package*.json ./backend
COPY ../client/package*.json ./client

RUN npm install --prefix ../backend

RUN npm install --prefix ../client

RUN npm --prefix ../client build

COPY . .

CMD ["npm", "run", "start", "--prefix", "../backend"]